- name: sysctl.conf permissions
  file:
     dest: "/etc/sysctl.conf"
     owner: root
     group: root
     mode: 0600

- name: sysctl.d permissions
  file:
     dest: "/etc/sysctl.d/"
     recurse: yes
     owner: root
     group: root
     mode: u=rwX,go=
  changed_when: false 

- name: sysctl hardening 
  sysctl:
     name: "{{ item.key }}"
     value: "{{ item.value }}"
     sysctl_set: yes
     reload: yes
     state: present
     ignoreerrors: yes  # ignore errors about unknown keys
  with_dict: "{{ sysctl_config }}"
  notify: sysctl flush routes

