- name: enable strongswan
  service:
    name: ipsec
    enabled: yes
    state: restarted

- name: restart strongswan
  service:
    name: ipsec
    state: restarted

- name: restart freeradius
  service:
    name: freeradius
    state: restarted
