- import_role:
    name: common/linux-proxy
- import_role:
    name: common/linux-hostname
- import_role:
    name: common/harden-ssh
- import_role:
    name: common/harden-sysctl
- import_role:
    name: common/sweeten
- import_role:
    name: common/tools
- import_role:
    name: common/ntp
- import_role:
    name: common/fail2ban
- import_role:
    name: common/linux-compact-memory
- import_role:
    name: common/linux-journal
