- include_role:
    name: common/linux-virtual
  when: host_type == 'virtual'
- include_role:
    name: common/linux-physical
  when: host_type == 'physical'
- import_role:
    name: common/harden-ssh
- import_role:
    name: common/harden-sysctl
- import_role:
    name: common/sweeten
- import_role:
    name: common/tools
- import_role:
    name: common/fail2ban
- import_role:
    name: common/linux-compact-memory
- import_role:
    name: common/linux-journal
