  - name: install some usefull tools
    apt: name="{{item}}" state=present
    with_items:
    - vim-nox
    - tcpdump
    - screen
    - bc
    - tcptraceroute
    - debian-keyring
    - links
    - nmap
    - patch
    - iptraf
    #- subversion
    - wget
    - cron
    - make
    - openssl-blacklist
    - mtr
    - netsniff-ng
    - git
    - iotop
    - sysstat
    - whois
