UserParameter=ntp.drift,/usr/local/bin/zabbix_ntp.sh drift
UserParameter=ntp.offset,/usr/local/bin/zabbix_ntp.sh offset "{{ ntp_servers[0] | default('pool.ntp.org') }}"
UserParameter=ntp.selected-peer,/usr/local/bin/zabbix_ntp.sh selected-peer
UserParameter=ntp.selected-delay,/usr/local/bin/zabbix_ntp.sh selected-delay
UserParameter=ntp.selected-offset,/usr/local/bin/zabbix_ntp.sh selected-offset
UserParameter=ntp.selected-strata,/usr/local/bin/zabbix_ntp.sh selected-strata
