- name: do we have apt.conf.d?
  stat:
   path: /etc/apt/apt.conf.d
  register: st

- name: set https proxy for apt
  lineinfile:
    path: /etc/apt/apt.conf.d/99proxy
    create: yes
    state: present
    regexp: "^Acquire::{{ item.proto }}::Proxy.*$"
    line: 'Acquire::{{ item.proto }}::Proxy "{{ item.proxy }}";'
  with_items:
    - proto: http
      proxy: "{{ proxy_env.http_proxy | default() }}"
    - proto: https
      proxy: "{{ proxy_env.https_proxy | default() }}"
    - proto: ftp
      proxy: "{{ proxy_env.ftp_proxy | default() }}"
  when: st.stat.exists

- name: do we have wget?
  stat:
   path: /etc/wgetrc
  register: st

- name: set proxy for wget
  lineinfile:
   path: /etc/wgetrc
   create: yes
   state: present
   regexp: "^{{ item.key }} *=.*$"
   line: '{{ item.key }} = {{ item.value }}'
   insertbefore: '^.?use_proxy'
  with_items:
   - { "key": "http_proxy", "value": "{{ proxy_env.http_proxy | default() }}" }
   - { "key": "https_proxy", "value": "{{ proxy_env.https_proxy | default() }}" }
   - { "key": "ftp_proxy", "value": "{{ proxy_env.ftp_proxy | default() }}" }
   - { "key": "no_proxy", "value": "{{ proxy_env.no_proxy | default() }}" }

   - { "key": "HTTP_PROXY", "value": "{{ proxy_env.HTTP_PROXY | default() }}" }
   - { "key": "HTTPS_PROXY", "value": "{{ proxy_env.HTTPS_PROXY | default() }}" }
   - { "key": "FTP_PROXY", "value": "{{ proxy_env.FTP_PROXY | default() }}" }
   - { "key": "NO_PROXY", "value": "{{ proxy_env.NO_PROXY | default() }}" }
  when: st.stat.exists

- name: do we have pip?
  stat:
   path: /etc/pip.conf
  register: st

- name: set proxy for pip
  ini_file:
   path: /etc/pip.conf
   section: global
   option: proxy
   value: '{{ proxy_host }}:{{ proxy_port }}'
   create: yes
   state: present

- name: set proxy for the shell
  lineinfile:
   path: /etc/environment
   regexp: "^{{ item.key }}=.*$"
   line: '{{ item.key }}="{{ item.value }}"'
  with_items:
   - { "key": "http_proxy", "value": "{{ proxy_env.http_proxy | default() }}" }
   - { "key": "https_proxy", "value": "{{ proxy_env.https_proxy | default() }}" }
   - { "key": "ftp_proxy", "value": "{{ proxy_env.ftp_proxy | default() }}" }
   - { "key": "no_proxy", "value": "{{ proxy_env.no_proxy | default() }}" }

   - { "key": "HTTP_PROXY", "value": "{{ proxy_env.HTTP_PROXY | default() }}" }
   - { "key": "HTTPS_PROXY", "value": "{{ proxy_env.HTTPS_PROXY | default() }}" }
   - { "key": "FTP_PROXY", "value": "{{ proxy_env.FTP_PROXY | default() }}" }
   - { "key": "NO_PROXY", "value": "{{ proxy_env.NO_PROXY | default() }}" }
