- name: install dependencies
  package:
    name: apt-transport-https
    state: present
  tags: install

- name: add thehive-project key
  apt_key:
    url: "https://raw.githubusercontent.com/TheHive-Project/TheHive/master/PGP-PUBLIC-KEY"
    keyring: /etc/apt/trusted.gpg.d/thehive.gpg
    state: present
  tags: install

- name: add thehive-project repo
  apt_repository:
    repo: "deb https://dl.bintray.com/thehive-project/debian-stable any main"
    update_cache: yes
  tags: install

- name: install cortex
  apt:
    name: cortex
    state: present
  tags: install

- name: prepare cortex-analyzers dir
  file:
    path: "{{ cortex.analyzers_dir }}"
    state: directory
  tags: install

- name: checkout cortex analyzers
  git:
    repo: "https://github.com/TheHive-Project/Cortex-Analyzers.git"
    dest: "{{ cortex.analyzers_dir }}"
  notify: restart cortex

- name: enable cortex service
  service:
      name: cortex
      enabled: yes
  tags: install
  notify: restart cortex

- name: configure cortex
  template:
    src: application.conf
    dest: /etc/cortex/application.conf
    owner: cortex
    mode: 0640
  tags: configure
  notify: restart cortex

- name: add cortex to docker group
  user:
    name: cortex
    groups: docker
    append: yes
  tags: install

