- name: install dependencies
  package:
    name: 
      - apt-transport-https
      - git
    state: present
  tags: install

- name: add thehive-project key
  apt_key:
    url: "https://raw.githubusercontent.com/TheHive-Project/Cortex/master/PGP-PUBLIC-KEY"
    keyring: /etc/apt/trusted.gpg.d/thehive.gpg
    state: present
  tags: install

- name: add thehive-project repo
  apt_repository:
    repo: "deb [arch=all] https://deb.thehive-project.org release main"
    update_cache: yes
  tags: install

- name: install cortex
  apt:
    name: cortex
    state: present
  tags: install

- name: prepare cortex-analyzers dir
  file:
    path: "{{ cortex_analyzers_dir }}"
    state: directory
  tags: install

- name: deploy cortex-tools
  copy:
    src: "{{ item }}"
    dest: "{{ cortex_analyzers_dir }}/{{ item }}"
  with_items:
    - env.example
    - compare-versions.sh
    - export-analyers.sh
    - pull-analyzers.sh

- name: enable cortex service
  service:
      name: cortex
      enabled: yes
  tags: install
  notify: restart cortex

- name: configure cortex
  template:
    src: application.conf
    dest: /etc/cortex/application.conf
    owner: cortex
    mode: 0640
  tags: configure
  notify: restart cortex

- name: add cortex to docker group
  user:
    name: cortex
    groups: docker
    append: yes
  tags: install

