#- name: add ondrej apache2 ppa
#  apt_repository:
#    repo: ppa:ondrej/apache2
#    state: present
#    update_cache: yes

#XXX: https://github.com/ansible/ansible/issues/42534
- name: add repo key
  apt_key:
    url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x4F4EA0AAE5267A6C"
    keyring: /etc/apt/trusted.gpg.d/ondrej.gpg
    state: present
  when: www_use_ondrej

- name: add apache2 repo
  apt_repository:
    repo: "deb http://ppa.launchpad.net/ondrej/apache2/ubuntu {{ ansible_distribution_release }} main"
    filename: php
    state: present
    update_cache: yes
  when: www_use_ondrej

- name: install packages
  apt:
    name:
      - apache2
      - apache2-utils
  notify: restart apache2

- name: enable apache2 modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
  - rewrite
  - ssl
  - actions
  - include
  - auth_digest
  - actions
  - proxy_fcgi
  - alias
  - vhost_alias
  notify: restart apache2

- name: configure apache2
  template:
    src: "{{ item }}"
    dest: "/etc/apache2/conf-available/{{ item }}"
  with_items:
  - php-fpm.conf
  - security.conf
  - ssl.conf
  notify: restart apache2

- name: configure apache default sites
  template:
    src: "000-default.conf"
    dest: "/etc/apache2/sites-available/000-default.conf"
  notify: restart apache2

- name: delete unused files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "/etc/apache2/sites-available/default-ssl.conf"
  - "/etc/apache2/sites-available/default-tls.conf"
  notify: restart apache2

- name: generate empty index.html
  copy:
    dest: "/var/www/html/index.html"
    content: ""
    group: www-data
    owner: www-data
    mode: 0400

#TODO: disable phpXXX-fpm.conf files
- name: enable apache2 configs
  shell: a2enconf {{ item }} || true
  changed_when: false
  with_items:
  - php-fpm
  notify: restart apache2

- name: disable mod_php 
  apache2_module:
    name: "{{ item }}"
    force: true
    state: absent
  with_items:
  - php5.6
  - php7.0
  - php7.1
  - php7.2
  - php7.3
  - php7.4
  - php8.0
  notify: restart apache2
  ignore_errors: yes

- name: disable autoindex 
  apache2_module:
    name: audoindex
    force: true
    state: absent
  when: www_disable_autoindex
  notify: restart apache2

