
# install php 
- include_tasks: php.yml 
  loop_control:
    loop_var: php_version
  with_items: "{{ php_versions }}"

# remove old php version
- include_tasks: php_remove.yml 
  loop_control:
    loop_var: php_version
  with_items: "{{ php_remove_versions }}"

- import_tasks: composer.yml 

# install and secure apache
- import_tasks: apache2.yml

