- name: add ondrej php ppa
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    update_cache: yes

# ## used in Ubuntu server >= 18.04
#- name: add php repo
#  block:
#    - name: add repo key
#      apt_key: 
#        url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x4F4EA0AAE5267A6C"
#        state: present
#
#   - name: add php repo
#      apt_repository:
#        repo: "deb http://ppa.launchpad.net/ondrej/php/ubuntu {{ ansible_distribution_release }} main"
#        filename: php
#        state: present
 
- name: install packages
  apt:
      name:
        - "php{{php_version}}-fpm"
        - "php{{php_version}}-cli"
        - "php{{php_version}}-intl"
        - "php{{php_version}}-curl"
        - "php{{php_version}}-gd"
        - "php{{php_version}}-mbstring"
        - "php{{php_version}}-zip"
        - "php{{php_version}}-mysql"
        - php-mcrypt
        - php-gettext
        - php-imagick 
        - imagemagick 
        - composer
  notify: restart php

- name: configure php.ini for CLI and defaul FPM
  template:
    src: "php{{php_version}}.ini"
    dest: "/etc/php/{{php_version}}/{{item}}/php.ini"
    owner: root
    mode: 755
  with_items:
  - fpm
  - cli

- name: enable php modules
  shell: "php{{php_version}}enmod {{ item }} || true"
  with_items:
  - mcrypt
  - mbstring
  notify: restart php

