- name: 
  debug:
    msg: |
      ## zabbix is our pet server now... don't be mean to it
      apt install gnupg postgresql-common apt-transport-https lsb-release wget
      /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
      echo "deb https://packagecloud.io/timescale/timescaledb/ubuntu/ $(lsb_release -c -s) main" | sudo tee /etc/apt/sources.list.d/timescaledb.list
      wget --quiet -O - https://packagecloud.io/timescale/timescaledb/gpgkey | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/timescaledb.gpg
      apt-get install timescaledb-2-loader-postgresql-15='2.9.*' timescaledb-2-postgresql-15='2.9.*'
      timescaledb-tune --quiet --yes
      systemctl restart postgresql
      sudo -u postgres psql
      \dx
      CREATE EXTENSION IF NOT EXISTS timescaledb;
      \dx
      apt-get install zabbix-server-pgsql zabbix-sql-scripts
      sudo -u postgres createuser --pwprompt zabbix
      # openssl rand -base64 15 and remember pw
      sudo -u postgres createdb -O zabbix zabbix
      zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix
      echo "CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;" | sudo -u postgres psql zabbix
      cat /usr/share/zabbix-sql-scripts/postgresql/timescaledb.sql | sudo -u zabbix psql zabbix
      apt-get install zabbix-frontend-phpphp8.1-pgsql zabbix-apache-conf
      # store pw into /etc/zabbix/zabbix_server.conf
