- name: install basic networking tools
  package:
    name:
    - ifupdown
    - bridge-utils
    - ifenslave
    - vlan
    state: present
  tags: install

- name: remove netplan
  package:
    name: netplan.io
    state: absent
  tags: install

- name: generate 70-persistent-net.rules
  template:
    src: 70-persistent-net.rules
    dest: /etc/udev/rules.d/70-persistent-net.rules
  notify: reboot host to apply networking changes
  tags: configure

- name: generate interfaces
  template: 
    src: interfaces
    dest: /etc/network/interfaces
  notify: reboot host to apply networking changes
  tags: configure

- name: generate mactab
  template: 
    src: mactab
    dest: /etc/network/mactab
  notify: reboot host to apply networking changes
  tags: configure

- name: disable systemd-networkd service
  systemd:
    name: systemd-networkd
    state: stopped
    enabled: no

