- name: install basic networking tools
  package:
    name: 
    - bridge-utils
    - ifupdown
    - ifenslave
    - vlan
    state: present
  tags: install

- name: remove netplan
  package:
    name:
    - netplan.io
    state: absent
  tags: install

- name: generate /etc/hosts
  template:
    src: hosts
    dest: /etc/hosts

- name: ifupdown configuration
  include_tasks: ifupdown.yml
  tags: configure

