- name: install basic networking tools
  package:
    name:
    - netplan.io
    - vlan
    state: present
  tags: install

- name: remove ifupdown
  package:
    name: 
    - ifupdown
    - bridge-utils
    state: absent
  tags: install

- name: generate netplan.yml
  template:
    src: netplan.yaml
    dest: /etc/netplan/01-netcfg.yaml
    mode: 0600
  notify:
  - reboot host to apply networking changes
  - netplan apply
  tags: configure

- name: remove old config files
  file:
    path: /etc/netplan/{{ item }}
    state: absent
  with_items:
    - 50-cloud-init.yaml
    - 10-interfaces.yaml
  tags: configure

- name: enable systemd services
  systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
  with_items:
    - systemd-networkd
    - networkd-dispatcher

- name: disable systemd services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    masked: yes
  with_items:
    - systemd-resolved

