- name: install basic networking tools
  package:
    name:
    - netplan.io
    - bridge-utils
    - vlan
    state: present
  tags: install

- name: remove ifupdown
  package:
    name: ifupdown
    state: absent
  tags: install

- name: generate netplan.yml
  template:
    src: netplan.yaml
    dest: /etc/netplan/01-netcfg.yaml
  notify:
  - reboot host to apply networking changes
  - netplan apply
  tags: configure

- name: remove old config files
  file:
    path: /etc/netplan/{{ item }}
    state: absent
  with_items:
    - 50-cloud-init.yaml
    - 10-interfaces.yaml
  tags: configure

