- name: install dependencies
  package:
    name: multipath-tools
    state: present
  tags: install

- name: deploy multipath-refresh.sh
  copy:
    src: multipath-refresh.sh
    dest: /usr/local/bin/multipath-refresh.sh
    mode: 0755 
    owner: root
  tags: install

- name: configure multipath.conf
  template:
      src: multipath.conf
      dest: /etc/multipath.conf
  register: multipath_conf
  tags: configure

- name: refresh targets
  shell: /usr/local/bin/multipath-refresh.sh
  when: multipath_conf.changed
  tags: configure
