- name: install dependencies
  package:
    name: 
    - multipath-tools
    - lsscsi
    state: present
  tags: install

- name: deploy custom scripts
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755 
    owner: root
  with_items:
    - multipath-refresh.sh
    - multipath-delete.sh
    - multipath-resize.sh
  tags: install

- name: configure multipath.conf
  template:
      src: multipath.conf
      dest: /etc/multipath.conf
  register: multipath_conf
  tags: configure

- name: refresh targets
  shell: /usr/local/bin/multipath-refresh.sh
  when: multipath_conf.changed
  tags: configure
