- name: add hlandau/rhea ppa
  apt_repository:
    repo: ppa:hlandau/rhea
    state: present
    update_cache: yes

- name: install acmetool
  package:
    name: acmetool
    state: present

- name: make sure /var/lib/acme/conf directory is present
  file:
    path: /var/lib/acme/conf/
    state: directory

- name: configure acmetool
  template:
    src: "{{ item }}"
    dest: "/var/lib/acme/conf/{{ item }}"
  with_items:
  - responses
  - target
  register: acmetool_config
  tags: configure

- name: reconfigure acmetool
  shell:
    acmetool quickstart --batch
  when: acmetool_config.changed  
  tags: configure

