- name: prepare directory for remote logs
  file:
    path: "{{ syslog_dir }}"
    state: "directory"
  tags: configure
  notify: restart syslog-ng

- name: configure syslog-ng
  template:
    src: "server.conf"
    dest: "/etc/syslog-ng/conf.d/server.conf"
  tags: configure
  notify: restart syslog-ng

- name: configure logrotate
  template:
    src: "logrotate.conf"
    dest: "/etc/logrotate.d/remote-logs"
  tags: configure
