 - name: pull docker-compose 
   file:
     path: /opt/minio-docker
     state: directory

 - name: generate docker-compose 
   copy:
     content: |
       version: '3.7'
       services:
         minio:
           image: quay.io/minio/minio:{{ minio_version }}
           command: server --console-address ":9001" /minio/data
           ports:
             - "8443:9000"
             - "443:9001"
           volumes:
             - data:/data
             - ./certs:/root/.minio/certs
           healthcheck:
             test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
             interval: 30s
             timeout: 20s
             retries: 3
           restart: unless-stopped
           environment:
             MINIO_ROOT_USER: "{{ minio_admin_user }}"
             MINIO_ROOT_PASSWORD: "{{ minio_admin_password }}"
             #VIRTUAL_HOST: "{{ inventory_hostname }}"
             #VIRTUAL_PORT: 8080
       volumes:
         data:
     dest: /opt/minio-docker/docker-compose.yml

 - name: run docker-compose
   shell: 
     docker-compose up -d && sleep 30
   args:
     chdir: /opt/minio-docker/

