- name:
  debug: var=ansible_distribution_major_version

- name: install python-mysqldb
  package:
    name:
    - python-mysqldb
    state: present
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version <= "18"

- name: install zabbix-proxy and python3-mysqldb
  package:
    name:
    - python3-mysqldb
    - zabbix-proxy-mysql
    state: present

- name: create zabbix database
  mysql_db:
    name: "{{ zabbix_proxy_db_name }}"
    encoding: utf8
    collation: utf8_bin
    state: present
  register: zabbix_proxy_db_present

- name: create zabbix user
  mysql_user:
    name: "{{ zabbix_proxy_db_user }}"
    password: "{{ zabbix_proxy_db_password }}"
    priv: "{{ zabbix_proxy_db_name }}.*:ALL"
    state: present

- name: import zabbix database
  mysql_db:
    name: "{{ zabbix_proxy_db_name }}"
    state: import
    target: /usr/share/doc/zabbix-proxy-mysql/schema.sql.gz
  when: zabbix_proxy_db_present.changed == True

- name: create zabbix server CA file
  copy:
    content: "{{ zabbix_server_ca_value }}"
    dest: "/etc/zabbix/ca.crt"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  when: zabbix_proxy_tls_mode == "cert"
  notify: restart zabbix-proxy

- name: create zabbix proxy cert file
  copy:
    content: "{{ zabbix_proxy_tls_cert_value }}"
    dest: "/etc/zabbix/zabbix_proxy.crt"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  when: zabbix_proxy_tls_mode == "cert"
  notify: restart zabbix-proxy

- name: create zabbix proxy key file
  copy:
    content: "{{ zabbix_proxy_tls_key_value }}"
    dest: "/etc/zabbix/zabbix_proxy.key"
    owner: zabbix
    group: zabbix
    mode: u=rw,g=r,o=
  when: zabbix_proxy_tls_mode == "cert"
  notify: restart zabbix-proxy

- name: create proxy PSK file
  copy:
    content: "{{ zabbix_proxy_psk }}"
    dest: "/etc/zabbix/zabbix_proxy.psk"
    owner: zabbix
    group: zabbix
    mode: u=rw,g=r,o=
  when: zabbix_proxy_tls_mode == "psk"
  notify: restart zabbix-proxy

- name: configure zabbix-proxy
  template:
    src: zabbix_proxy.conf 
    dest: /etc/zabbix/zabbix_proxy.conf
    owner: zabbix
    group: zabbix
    mode: u=rw,g=r,o=
  notify: restart zabbix-proxy

- name: add proxy to zabbix server
  become: false
  environment:
    # this is going from your own computer directly to server without proxy
    http_proxy: ""
    https_proxy: ""
  local_action:
    module: zabbix_proxy
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_admin_login }}"
    login_password: "{{ zabbix_admin_password }}"
    proxy_name: "{{ zabbix_proxy }}"
    status: active
    state: present
    description: "zabbix proxy for sensor/agent {{ zabbix_proxy }}"
    interface:
        useip: 1
        ip: "{{ zabbix_proxy_addr | default(ansible_default_ipv4.address) }}"
        port: "10051"
    tls_connect: PSK # psk
    tls_accept: PSK  # psk
    tls_psk_identity: "{{ zabbix_proxy_psk_identity }}"
    tls_psk: "{{ zabbix_proxy_psk | default('00000000000000000000000000000000')}}"
    validate_certs: false
  notify: restart zabbix-proxy
  tags: configure

- name: enable and start zabbix proxy service
  systemd:
    name: zabbix-proxy
    enabled: true
    state: started

