- name:
  debug: var=ansible_distribution_major_version

- name: install zabbix-proxy
  package:
    name:
      - zabbix-proxy-pgsql
      - zabbix-sql-scripts
      - python3-psycopg2
    state: present

- name: Create PostgreSQL user
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ zabbix_proxy_db_user }}"
    password: "{{ zabbix_proxy_db_password }}"
    role_attr_flags: LOGIN

- name: Create PostgreSQL database
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ zabbix_proxy_db_name }}"
    owner: "{{ zabbix_proxy_db_user }}"
    encoding: UTF8
    state: present
  register: res

- name: Import SQL file into database
  community.postgresql.postgresql_db:
    login_user: "{{ zabbix_proxy_db_user }}"
    login_password: "{{ zabbix_proxy_db_password }}"
    login_host: localhost
    name: "{{ zabbix_proxy_db_name }}"
    state: restore
    target: "{{ zabbix_proxy_schema_file }}"
  when: res.changed

- name: create zabbix server CA file
  copy:
    content: "{{ zabbix_server_ca_value }}"
    dest: "/etc/zabbix/ca.crt"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  when: zabbix_proxy_tls_mode == "cert"
  notify: restart zabbix-proxy

- name: create zabbix proxy cert file
  copy:
    content: "{{ zabbix_proxy_tls_cert_value }}"
    dest: "/etc/zabbix/zabbix_proxy.crt"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  when: zabbix_proxy_tls_mode == "cert"
  notify: restart zabbix-proxy

- name: create zabbix proxy key file
  copy:
    content: "{{ zabbix_proxy_tls_key_value }}"
    dest: "/etc/zabbix/zabbix_proxy.key"
    owner: zabbix
    group: zabbix
    mode: u=rw,g=r,o=
  when: zabbix_proxy_tls_mode == "cert"
  notify: restart zabbix-proxy

- name: create proxy PSK file
  copy:
    content: "{{ zabbix_proxy_psk }}"
    dest: "/etc/zabbix/zabbix_proxy.psk"
    owner: zabbix
    group: zabbix
    mode: u=rw,g=r,o=
  when: zabbix_proxy_tls_mode == "psk"
  notify: restart zabbix-proxy

- name: configure zabbix-proxy
  template:
    src: zabbix_proxy.conf 
    dest: /etc/zabbix/zabbix_proxy.conf
    owner: zabbix
    group: zabbix
    mode: u=rw,g=r,o=
  notify: restart zabbix-proxy

- name: enable and start zabbix proxy service
  systemd:
    name: zabbix-proxy
    enabled: true
    state: started
  when: not ansible_check_mode

