
- package:
   name: apt-transport-https
   state: present

- name: check if zabbix-release is available
  command: apt list --installed zabbix-release
  register: res
  check_mode: no
  changed_when: False
  ignore_errors: True

- debug: msg="installed zabbix-release version={{ res.stdout | regex_search(':[0-9].[0-9]') }} expected zabbix_version={{ zabbix_version }}"

- name: check if we need to reinstall zabbix-release
  set_fact:
    reinstall_zabbix: "{{ res.stdout | regex_search(':[0-9].[0-9]') != ':'+zabbix_version }}"
    check_mode: no

- debug: msg="reinstall_zabbix={{ reinstall_zabbix }}"

- name: remove old zabbix-release
  apt:
      name: zabbix-release
      state: absent
      purge: yes
      autoremove: yes
  when: reinstall_zabbix

- name: remove old zabbix-release file
  file:
    path: /tmp/zabbix-release.deb
    state: absent
  when: reinstall_zabbix

- name: download zabbix-release package
  get_url:
    url: "{{ zabbix_release_url }}"
    dest: "/tmp/zabbix-release.deb"
  when: reinstall_zabbix

- name: install zabbix-release.deb
  apt:
    deb: "/tmp/zabbix-release.deb"
  when: reinstall_zabbix

- name: apt-get update
  apt:
    update_cache: yes
  when: reinstall_zabbix
