- name: install dependencies
  package:
    name:
    - apt-transport-https
    - python3-docker
    state: present
  tags: install

- name: add docker key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    keyring: /etc/apt/trusted.gpg.d/docker.gpg
    state: present
  tags: install

- name: add docker repo
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    update_cache: yes
  tags: install

- name: remove docker.io
  apt:
    name:
    - docker.io
    state: absent
  tags: install

- name: install docker-ce, tools and dependencies
  apt:
    name:
    - docker-ce
    - docker-compose
    - python3-pip
    state: present
  tags: install

- name: install docker & docke-compose python bindings
  pip:
    name:
    - docker
    - docker-compose
  tags: install

- name: expose docker daemon
  include_tasks: expose-daemon.yml
  when: 'docker_expose_daemon | default(false)'

