- name: install dependencies
  package:
    name:
    - apt-transport-https
    - python3-docker
    state: present
  tags: install

- name: add docker key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    keyring: /etc/apt/trusted.gpg.d/docker.gpg
    state: present
  tags: install

- name: add docker repo
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    update_cache: yes
  tags: install

- name: remove docker.io and docker-compose
  apt:
    name:
    - docker.io
    - docker-compose
    state: absent
  tags: install

- name: install docker-ce and dependencies
  apt:
    name:
    - docker-ce
#FIXME: ubuntu24.04
#    - python3-pip
    state: present
  tags: install

#FIXME: ubuntu24.04
#- name: install docker & docke-compose python bindings
#  pip:
#    name:
#    - docker
#  tags: install

- name: expose docker daemon
  include_tasks: expose-daemon.yml
  when: 'docker_expose_daemon | default(false)'

