- name: install suricata dependencies
  package:
    name:
    - software-properties-common
    - apt-transport-https
    - jq
  tags: install

# XXX: if not honoring the proxy envs use this instead:
# should be tested every once in a while, if it got fixed...
- name: add suricata-stable repository (respecting proxy)
  when: ansible_env.http_proxy is defined
  shell: add-apt-repository ppa:oisf/suricata-stable --update

- name: add suricata-stable repository
  when: ansible_env.http_proxy is not defined
  apt_repository:
    repo: ppa:oisf/suricata-stable
    state: present
    update_cache: yes
  tags: install

- name: install suricata
  package:
    name:
    - suricata
  tags: install
  notify: restart suricata

- name: deploy scripts
  template:
    src: "{{ item }}"
    dest: "/usr/local/bin/suricata-{{ item }}"
    mode: 0755
  with_items:
  - nic.sh
  - set-affinity.sh
  - prune-eve-logs.sh
  tags:
  - install
  - configure

- name: deploy suricata cron.d for irqs
  copy:
    content: |
      0 2 * * * root /usr/local/bin/suricata-prune-eve-logs.sh
    dest: /etc/cron.d/suricata-prune-eve-logs
    mode: 0750

- name: update suricata-update soures
  shell: suricata-update update-sources
  tags: suricata-update

- name: enable suricata-update sources
  shell: "suricata-update enable-source {{ item | quote }}"
  ignore_errors: True
  tags: suricata-update
  with_items: "{{ suricata_sources }}"

- name: run suricata-update
  shell: suricata-update
  tags: suricata-update
  notify: restart suricata

- name: configure suricata
  template:
      src: suricata.yaml
      dest: /etc/suricata/suricata.yaml
      mode: 0644
  tags: configure
  notify: restart suricata

- name: LOCAL RULE - empty file
  file:
    path: /etc/suricata/local.rules
    mode: 0644
    owner: root
    group: root
    state: touch
    access_time: preserve
    modification_time: preserve
  tags: always

- name: configure suricata (threshold.config)
  template:
      src: threshold.config
      dest: /etc/suricata/threshold.config
      mode: 0644
  tags: configure
  notify: restart suricata

- name: configure suricata (.config)
  template:
      src: classification.config
      dest: /etc/suricata/classification.config
      mode: 0644
  tags: configure
  notify: restart suricata

- include_tasks:
    file: set_affinity.yml
  when: suricata_set_affinity

- name: configure logrotate
  copy:
      src: logrotate.conf
      dest: /etc/logrotate.d/suricata
  tags: configure
