- name: add suricata-stable repository
  shell:  add-apt-repository ppa:oisf/suricata-stable --update

# This is not working with proxy!
#- name: add suricata-stable repository
#  apt_repository:
#    repo: ppa:oisf/suricata-stable
#    state: present
#    update_cache: yes
#  tags: install

- name: add suricata-stable repository apt-key
  shell: "apt-key adv {%if proxy_env is defined %}--keyserver-options http-proxy={{ proxy_env.http_proxy }}{% endif %} --recv-keys --no-tty --keyserver hkp://keyserver.ubuntu.com:80 9F6FC9DDB1324714B78062CBD7F87B2966EB736F"

- name: install suricata with dependencies
  package: 
    name:
    - software-properties-common
    - apt-transport-https
    - jq
    - suricata
  tags: install

- name: deploy suricata-nic.sh
  template:
    src: nic.sh
    dest: /usr/local/bin/suricata-nic.sh
    mode: 0755
  tags: install

- name: update suricata-update soures
  shell: suricata-update update-sources
  tags: suricata-update

- name: enable suricata-update sources
  shell: "suricata-update enable-source {{ item | quote }}"
  ignore_errors: True
  tags: suricata-update
  with_items: "{{ suricata_sources }}"

- name: run suricata-update 
  shell: suricata-update 
  tags: suricata-update
  notify: restart suricata

- name: configure suricata
  template:
      src: suricata.yaml
      dest: /etc/suricata/suricata.yaml
      mode: 0644
  tags: configure
  notify: restart suricata

- name: configure suricata (threshold.config)
  template:
      src: threshold.config
      dest: /etc/suricata/threshold.config
      mode: 0644
  tags: configure
  notify: restart suricata

- name: configure suricata (.config)
  template:
      src: classification.config
      dest: /etc/suricata/classification.config
      mode: 0644
  tags: configure
  notify: restart suricata

- include_tasks:
    file: set_affinity.yml
  when: suricata_set_affinity

- name: configure logrotate
  copy:
      src: logrotate.conf
      dest: /etc/logrotate.d/suricata
  tags: configure
