- name: generate config files
  template:
    src: "{{ item }}"
    dest: "/etc/config/{{ item }}"
  with_items:
    - dropbear
  tags: configure

- name: remove invalid files
  file:
    path: "/etc/config/{{ item }}"
    state: absent
  with_items:
   - firewall
   - luci
   - rpcd
   - ucitrack
   - uhttpd
  tags: configure
