- name: install bacula and dependencies (pre-bionic)
  package: 
    name: "{{ item }}" 
    state: present
  with_items:
  - mysql-server
  - bacula-director-mysql
  - bacula-sd-mysql
  - bacula-fd
  - bacula-client
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release != 'bionic'

- name: install bacula and dependencies (bionic)
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - mysql-server
  - bacula-director-mysql
  - bacula-server
  - bacula-sd
  - bacula-fd
  - bacula-client
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'bionic'

- name: setup mysql user
  mysql_user:
    name: bacula
    password: "{{ bacula_db_passwd }}"
  notify: restart bacula services

- name: copy bacula director settings
  template:
    src: bacula-dir.conf
    dest: /etc/bacula/bacula-dir.conf
    owner: bacula
    group: bacula
    mode: u=rw,g=r,o=
  notify: restart bacula services

- name: copy bacula storage daemon settings
  template:
    src: bacula-sd.conf
    dest: /etc/bacula/bacula-sd.conf
    owner: bacula
    group: bacula
    mode: u=rw,g=r,o=
  notify: restart bacula services

- name: copy bacula file daemon settings
  template:
    src: bacula-fd.conf
    dest: /etc/bacula/bacula-fd.conf
    owner: bacula
    group: bacula
    mode: u=rw,g=r,o=
  notify: restart bacula services

- name: copy bacula console settings
  template:
    src: bconsole.conf
    dest: /etc/bacula/bconsole.conf
    owner: bacula
    group: bacula
    mode: u=rw,g=r,o=
  notify: restart bacula services

- name: create ssl directory
  file:
    path: /etc/bacula/ssl
    state: directory

- name: setup ssl certs
  copy:
    src: "{{ item }}"
    dest: /etc/bacula/ssl
    owner: bacula
    group: bacula
    mode: u=rw,g=rw,o=
  notify: restart bacula services
  with_items:
    - "{{ root_dir }}/files/backup/{{ backup_group }}/{{ inventory_hostname }}.pem"
    - "{{ root_dir }}/files/backup/{{ backup_group }}/{{ inventory_hostname }}.crt"
    - "{{ root_dir }}/files/backup/{{ backup_group }}/ca.crt"

