############################
# ELASTICSEARCH:
############################
# all tasks for elasticsearch 
############################
# PREREQUISITE:
############################
# VM with installed OS must exist 
# with enough DISK (1TB prod, 100GB test) space for elastic data
# with enough RAM (35GB prod, 8GB test) for java VM 
############################
# RUN:
############################
# cd $ANSIBLE_DIR
# ansible-playbook playbooks/elk/elasticsearch/playbook.yml -i inventory/dev/hosts -l elastic79-1.dev.sk-cert.sk -vvv -CD --step
# ansible-playbook playbooks/elk/elasticsearch/playbook.yml -i inventory/dev/hosts -l elasticsearch79 -v
############################
# PLAYBOOK:
############################

---

- hosts: elasticsearch79
  gather_facts: true
  environment: "{{ proxy_env }}"
  tasks:
     - include_role: 
          name: common/deploy-cert
       vars:
          dest_name: "{{ inventory_hostname }}"
          dest_dir: /etc/elasticsearch/certs/
       tags: never
        
     - include_role: 
         name: common/elk/elasticsearch
         tasks_from: "main_79" # this is new version
         defaults_from: "main_79" # this is new version
       vars: 
         users: "{{ admins }}"
         node_list: "{{ groups[elastic.cluster_group] }}"
         master_nodes: "{{ groups[elastic.cluster_group] }}"
         
#       tags: 
#          - never
#          - elk
