- name: install fail2ban
  package: 
    name: fail2ban
    state: present
  notify: restart fail2ban
  tags: install

- name: configure fail2ban
  template:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    owner: root 
    group: root 
    mode: 0644
  notify: restart fail2ban
  tags: configure

