- name: install dependencies
  package:
      name:
      - apt-transport-https
      state: present
  tags: install

- name: add grafana key
  apt_key:
      url: "https://packages.grafana.com/gpg.key"
      state: present
  tags: install

- name: add grafana repo
  apt_repository:
      repo: "deb https://packages.grafana.com/oss/deb stable main"
      update_cache: yes
  tags: install

- name: install grafana
  package:
      name: grafana
      state: present
  tags: install
  notify: 
  - enable grafana
  - restart grafana

- name: configure grafana
  template:
      src: grafana.ini
      dest: /etc/grafana/grafana.ini
  tags: configure
  notify: restart grafana

