- name: defaults
  set_fact:
    suricata_huge: {}
    suricata_small: {}

- name: suricata fix permissions and group
  file:
     path: "/var/log/suricata"
     group: zabbix
     mode: "a+x"
     state: "directory"
  when: '"suricata" in group_names'

- name: suricata fix permissions
  file:
     path: "/var/lib/suricata/rules"
     mode: "a+x"
     state: "directory"
  when: '"suricata" in group_names'

- name: openvpn check status file presence
  file:
     path: "/var/run/openvpn/server.status"
     state: "file"
  failed_when: false
  register: openvpn_status_file

- name: openvpn fix permissions
  file:
     path: "/var/run/openvpn/server.status"
     group: "zabbix"
     mode: "g+r"
     state: "file"
  when: openvpn_status_file is defined and openvpn_status_file.state is defined and openvpn_status_file.state == 'file'
