- name: defaults
  set_fact:
    suricata_huge: {}
    suricata_small: {}

- name: suricata fix permissions and group
  file:
     path: "/var/log/suricata"
     group: zabbix
     mode: "a+x"
     state: "directory"
  when: suricata is defined and 'suricata' in group_names

- name: suricata fix permissions
  file:
     path: "/var/lib/suricata/rules"
     mode: "a+x"
     state: "directory"
  when: suricata is defined and 'suricata' in group_names

- name: openvpn check status file presence
  file:
     path: "/var/run/openvpn/server.status"
     state: "file"
  register: openvpn_status_file

- name: openvpn fix permissions
  file:
     path: "/var/run/openvpn/server.status"
     group: "zabbix"
     mode: "g+r"
     state: "file"
  when: openvpn_status_file.state == 'file'

- name: docker fix group
  user:
    name: "zabbix"
    group: "docker"
  when: "'docker' in group_names"

# old configs
- name: Remove old config dir
  file:
    path: /etc/zabbix/zabbix_agent.d
    state: absent

# unused configs
- name: Remove unused config dir
  file:
    path: /etc/zabbix/zabbix_agent2.d
    state: absent
  tags: never

- name: Create config dir
  file:
    path: /etc/zabbix/zabbix_agent2.d
    state: directory
    owner: zabbix
    group: zabbix
    mode: 0775
  tags: never

# we are using some templates which needs this old configs
- name: old configs to zabbix_agent2.d
  copy:
    src: "zabbix_agent2.d"
    dest: /etc/zabbix
    owner: zabbix
    group: zabbix
    mode: 0640
    directory_mode: 0755
  tags: never
