- set_fact:
      zabbix_linked_templates:  "{{ zabbix_template_definitions | json_query('*.template') | unique }}"

- debug: msg="zabbix_url={{ zabbix_url }}", verbosity=1
- debug: msg="zabbix_admin_login={{ zabbix_admin_login }}", verbosity=1
#- debug: msg="zabbix_linked_templates={{ zabbix_linked_templates }}", verbosity=1
- debug: msg="zabbix_template_definitions={{ zabbix_template_definitions }}", verbosity=1
- debug: msg="zabbix_linked_templates={{ zabbix_linked_templates }}", verbosity=1

- name: add host to zabbix server
  become: false
  environment:
    # this is going from your own computer directly to server without proxy
    http_proxy: ""
    https_proxy: ""
  local_action:
    module: zabbix_host
    force: yes
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_admin_login }}"
    login_password: "{{ zabbix_admin_password }}"
    host_name: "{{ inventory_hostname }}"
    visible_name: "{{ inventory_hostname }}"
    host_groups: "{{ zabbix_groups }}"
    link_templates: "{{ zabbix_linked_templates }}"
    status: enabled
    state: present
    interfaces:
      - type: agent
        main: 1
        useip: 1
        ip: "{{ zabbix_agent_addr | default(ansible_default_ipv4.address) }}"
        dns: ""
        port: "10050"
    tls_connect: 2 # psk
    tls_accept: 2  # psk
    tls_psk_identity: "{{ inventory_hostname }}"
    tls_psk: "{{ zabbix_agent_psk | default('00000000000000000000000000000000')}}"
    proxy: "{{ zabbix_proxy | default('') }}"
    validate_certs: false
  tags: configure
  when: not ansible_check_mode

- name: Create zabbix macros
  become: false
  local_action:
    module: zabbix_hostmacro
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_admin_login }}"
    login_password: "{{ zabbix_admin_password }}"
    host_name: "{{ inventory_hostname }}"
    macro_name: "{{ item['macro_name'] }}"
    macro_value: "{{ item['macro_value'] }}"
    state: present
    validate_certs: false
  with_items: "{{ zabbix_macros | default([]) }}"
  tags: configure
