- name: create user
  user: 
    name: "{{ www_user }}"
    home: "/var/www/{{ www_domain }}"
    groups: "www-data"
    shell: "/bin/false"
    createhome: no 
    state: present

- name: add www-data to new group
  user:
    name: www-data
    groups: "{{ www_user }}"
    append: yes

- name: create domain directories
  file: 
    path: "/var/www/{{ www_domain }}/{{ item }}" 
    state: directory 
    owner: "{{ www_user }}"
    group: "{{ www_user }}"
  with_items:
    - "/"
    - "www/"
    - "_/"
  
- name: create redirection via .htaccess
  template: 
    src: "htaccess_redirect.j2" 
    dest: "/var/www/{{ www_domain }}/_/.htaccess"
    owner: "{{ www_user }}"
    group: "{{ www_user }}"

- name: create php-fpm pool
  template:
    src: "pool.conf.j2"
    dest: "/etc/php/{{ www_php_version }}/fpm/pool.d/{{ www_user }}.conf"
  notify:
    - restart php

- name: create vhost 
  template:
    src: "domain.conf.j2"
    dest: "/etc/apache2/sites-available/400-{{ www_domain }}.conf"
  notify:
    - restart apache

- name: append extra vhost configuration
  blockinfile:
    dest: "/etc/apache2/sites-available/400-{{ www_domain }}.conf"
    block: "{{ lookup('file', 'files/www-domain-append/{{ www_domain }}') }}"
  ignore_errors: yes

- name: enable vhost
  raw: a2ensite "400-{{ www_domain }}.conf"

