
- name: check if lv already exists
  stat:
    path: /dev/{{ drbd_vg }}/{{ drbd_res_name }}
  check_mode: no
  register: lv_status

- name: prepare lv
  lvol:
    lv: "{{ drbd_res_name }}"
    vg: "{{ drbd_vg }}"
    size: "{{ drbd_size }}"
  when: not lv_status.stat.exists

- name: prepare luks
  community.crypto.luks_device:
    device: "/dev/{{ drbd_vg }}/{{ drbd_res_name }}"
    name: "luks-{{ drbd_res_name }}"
    state: present
    type: luks2
    passphrase: "{{ drbd_luks2_pass }}"
  when:
    - drbd_luks2_pass is defined
    - not lv_status.stat.exists

- name: make sure luks is ready
  community.crypto.luks_device:
    device: "/dev/{{ drbd_vg }}/{{ drbd_res_name }}"
    name: "luks-{{ drbd_res_name }}"
    state: opened
    passphrase: "{{ drbd_luks2_pass }}"
  register: lv_luks_status
  when:
    - drbd_luks2_pass is defined

- name: luks is not ready
  fail:
    msg: "LUKS not ready on {{ drbd_res_name }}"
  when:
    - drbd_luks2_pass is defined
    - not lv_luks_status.name

- name: create resource config
  template:
    src: "resource"
    dest: "/etc/drbd.d/{{ drbd_res_name }}.res"
  tags: configure

- name: write drbd metadata
  shell:
    echo yes | drbdadm create-md {{ drbd_res_name }}
  when: not lv_status.stat.exists

- name: make resource primary
  shell:
    drbdadm up {{ drbd_res_name }}
  when: not lv_status.stat.exists

- name: make resource primary
  shell:
    drbdadm -- --overwrite-data-of-peer primary {{ drbd_res_name }}
  when: ( not lv_status.stat.exists ) and drbd_primary_host == inventory_hostname

- name: make resource secondary
  shell:
    drbdadm secondary {{ drbd_res_name }}
  when: ( not lv_status.stat.exists ) and drbd_primary_host != inventory_hostname
  # -- --discard-my-data connect

