- name: make sure vim-tiny is installed
  package:
    name: vim-tiny
    state: present
  tags: install

- name: check for default editor
  stat:
    path: /etc/alternatives/editor
  tags: configure
  check_mode: no
  register: alternatives_editor
  when: ansible_os_family == 'Debian'

- name: make sure vim is default editor
  shell:
    update-alternatives --set editor /usr/bin/vim.tiny
  when:
  - ansible_os_family == 'Debian'
  - alternatives_editor.stat.lnk_target != '/usr/bin/vim.tiny'
  tags: configure

- name: restore original vimrc
  ansible.builtin.apt:
    name: vim-common
    state: present
    install_recommends: false
    dpkg_options: force-confmiss

- name: remove old vim configuration
  file:
    path: "/etc/vim/vimrc.local"
    state: absent
  tags: configure

- name: fancy .profile for root
  template:
    src: dotprofile
    dest: "/root/.profile"
    owner: "root"
    group: "root"
    mode: 0640
  tags: configure

- name: fancy .vimrc for root
  copy:
    src: "vimrc"
    dest: "/root/.vimrc"
  tags: configure

- name: set issue/motd/issue.net message
  copy:
    content: "{{ issue }}"
    dest: "{{ item }}"
    owner: "root"
    group: "root"
    mode: 0644
  tags: configure
  with_items:
    - /etc/issue
    - /etc/motd
    - /etc/issue.net
