- name: install ns packages
  package: 
    name: 
    - bind9
    - bind9utils
  tags: install

- name: configure bind
  template: 
    src: "{{ item }}"
    dest: "/etc/bind/{{ item }}"
  with_items:
  - named.conf.local
  - named.conf.options
  notify: restart bind
  tags: configure

- name: prepare directories
  file:
      path: "{{ item.path }}"
      state: directory
      owner: "{{ item.owner }}"
      group: bind 
      mode: "{{ item.mode }}"
  with_items:
  - path: "/etc/bind/master/"
    owner: bind
    mode: "0750"
  - path: "/etc/bind/"
    owner: root
    mode: "02775"
  tags: install

- name: generate zone files
  template:
    src: "{{ root_dir }}/files/ns-zones/{{ item }}"
    dest: "/etc/bind/master/{{ item }}"
    owner: bind 
    group: bind 
    mode: 0640
  with_items: "{{ ns_master_zones }}"
  notify: restart bind
  tags: configure

