- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/semaphore-docker

- name: generate docker-compose.yml
  template: 
    src: docker-compose.yml
    dest: /opt/semaphore-docker/docker-compose.yml

- name: run docker compose
  shell: 
    echo "docker compose up -d && sleep 10"
  args:
    chdir: /opt/semaphore-docker/

