---

- name: establish OpenJDK repo
  when: ansible_distribution_major_version | int < 18
  apt_repository:
    repo: "ppa:openjdk-r/ppa"
    filename: "openjdk"
  tags: install

- name: install dependencies
  package:
    name:
    - apt-transport-https
    - openjdk-11-jre-headless
    state: present
  tags: install

- name: establish elasticsearch repo key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    id: D27D666CD88E42B4
    state: present
  tags: install

- name: establish elasticsearch repo
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{ elastic.version | default(6) }}.x/apt stable main"
    filename: "elastic"
  tags: install
