- name: establish https transport for apt
  package:
    name: apt-transport-https
    state: present
  tags: install

- name: establish elasticsearch repo key
  apt_key: 
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present
  tags: install

- name: establish elasticsearch repo
  copy:
    src: elastic-repo.list 
    dest: /etc/apt/sources.list.d/elastic-6.x.list
    mode: preserve
  register: apt_update
  tags: install

- name: udpate repositories
  apt:
    update_cache: yes
  tags: install
  when: apt_update.changed

