---

- name: install dependencies
  package:
    name:
    - apt-transport-https
    state: present
  tags: install

- name: establish elasticsearch repo key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    id: D27D666CD88E42B4
    state: present
  tags: install

- name: establish elasticsearch repo
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{ elastic.version | default(7) }}.x/apt stable main"
    filename: "elastic"
    update_cache: yes
  tags: install
