- name: unset https proxy for apt
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/apt/apt.conf.d/00proxy
    - /etc/apt/apt.conf.d/01proxy
    - /etc/apt/apt.conf.d/50proxy
    - /etc/apt/apt.conf.d/99proxy
    - /etc/apt/apt.conf.d/90curtin-aptproxy
    - /etc/apt/apt.conf.d/proxy.conf
    - /usr/lib/environment.d/99-environment.conf

- name: do we have wget?
  stat:
    path: /etc/wgetrc
  register: st

- name: unset proxy for wget
  lineinfile:
    path: /etc/wgetrc
    state: absent
    regexp: "^{{ item }} *=.*$"
  with_items:
  - "http_proxy"
  - "https_proxy"
  - "ftp_proxy"
  - "no_proxy"
  - "HTTP_PROXY"
  - "HTTPS_PROXY"
  - "FTP_PROXY"
  - "NO_PROXY"
  when: st.stat.exists

- name: do we have pip?
  stat:
   path: /etc/pip.conf
  register: st

- name: unset proxy for pip
  ini_file:
    path: /etc/pip.conf
    section: global
    option: proxy
    state: absent

- name: unset proxy for the shell
  lineinfile:
    path: /etc/environment
    state: absent
    regexp: "^{{ item }}=.*$"
  with_items:
  - "http_proxy"
  - "https_proxy"
  - "ftp_proxy"
  - "no_proxy"
  - "HTTP_PROXY"
  - "HTTPS_PROXY"
  - "FTP_PROXY"
  - "NO_PROXY"
