- name: remove rsyslog
  package: 
    name: rsyslog
    state: absent
  tags: install

- name: install syslog-ng
  package: 
    name: 
    - syslog-ng-core 
    - syslog-ng
    - logrotate
    state: present
  tags: install
  notify: restart syslog-ng

- name: configure syslog-ng
  template:
    src: "options.conf"
    dest: "/etc/syslog-ng/conf.d/options.conf"
  tags: configure
  notify: restart syslog-ng

- name: configure logrotate
  template:
    src: "logrotate"
    dest: "/etc/logrotate.d/syslog-ng"
  tags: configure

- name: ensure /var/log/news dir exists
  file:
    state: directory
    path: /var/log/news
    owner: root
    group: root
    mode: '0755'
  tags: configure
