 - name: pull docker-compose 
   git:
     repo: https://github.com/netbox-community/netbox-docker.git
     dest: /opt/netbox-docker
     version: release

 - name: generate docker-compose override
   copy:
     content: |
       version: '3.4'
       services:
         redis:
           restart: unless-stopped
         redis-cache:
           restart: unless-stopped
         postgres:
           restart: unless-stopped
         nginx-proxy:
           image: jwilder/nginx-proxy
           restart: unless-stopped
           ports:
             - "80:80"
             - "443:443"
           volumes:
             - /var/run/docker.sock:/tmp/docker.sock:ro
             - /opt/nginx-proxy-ssl/:/etc/nginx/certs:ro
         netbox-worker:
           restart: unless-stopped
         netbox-housekeeping:
           restart: unless-stopped
         netbox:
           restart: unless-stopped
           environment:
             REMOTE_AUTH_ENABLED: "true"
             REMOTE_AUTH_BACKEND: "netbox.authentication.LDAPBackend"
             AUTH_LDAP_SERVER_URI: "{{ netbox_ldap_server_uri }}"
             AUTH_LDAP_BIND_DN: "{{ netbox_ldap_bind_dn }}"
             AUTH_LDAP_BIND_PASSWORD: "{{ netbox_ldap_bind_password }}"
             AUTH_LDAP_USER_SEARCH_BASEDN: "ou=users,{{ netbox_ldap_base }}"
             AUTH_LDAP_USER_SEARCH_ATTR: "uid"
             LDAP_IGNORE_CERT_ERRORS: "true"
             #AUTH_LDAP_GROUP_SEARCH_BASEDN: "ou=groups,{{ netbox_ldap_base }}"
             #AUTH_LDAP_MIRROR_GROUPS: "true"
             AUTH_LDAP_REQUIRE_GROUP_DN: "cn=AppIpamUsers,ou=groups,{{ netbox_ldap_base }}"
             AUTH_LDAP_IS_ADMIN_DN: "cn=AppIpamAdmins,ou=groups,{{ netbox_ldap_base }}"
             AUTH_LDAP_IS_SUPERUSER_DN: "cn=AppIpamAdmins,ou=groups,{{ netbox_ldap_base }}"
             CHANGELOG_RETENTION: 1825
             VIRTUAL_HOST: "{{ inventory_hostname }}"
             VIRTUAL_PORT: 8080
     dest: /opt/netbox-docker/docker-compose.override.yml

 - name: run docker-compose
   shell: 
     docker-compose up -d && sleep 120
   args:
     chdir: /opt/netbox-docker/

