 - name: pull netbox-docker 
   git:
     repo: https://github.com/netbox-community/netbox-docker.git
     dest: /opt/netbox-docker
     version: release

 - name: generate docker-compose override
   template:
     src: docker-compose.override.yml
     dest: /opt/netbox-docker/docker-compose.override.yml

# - name: run docker compose
#   shell: 
#     docker compose up -d && sleep 120
#   args:
#     chdir: /opt/netbox-docker/
#
