- name: get vulcanizer
  shell: |
    export GOPATH=$HOME/go
    export PATH=$PATH:$GOPATH/bin
    export PATH=$PATH:/usr/local/go/bin
    export PATH=$PATH:/usr/lib/go-1.11/bin
    GO111MODULE=off go get -u github.com/golang/dep/cmd/dep
    export GO111MODULE="on"
    go get github.com/github/vulcanizer
    #cd go/src/github.com/github/vulcanizer/
    #./script/bootstrap
  args:
    creates: /root/go/bin/vulcanizer
  tags: install
