- name: add elastic apt keys
  apt_key: 
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present
  tags: install

- name: add elastic repository
  copy:
    src: elastic-repo.list 
    dest: /etc/apt/sources.list.d/elastic-6.x.list
    mode: preserve
  tags: install

- name: update apt cache
  apt:
    update_cache: yes

- name: install elastic
  import_tasks: "elastic/install.yml"
  tags: install

- name: configure elastic
  import_tasks: "elastic/configure.yml"
  tags: configure

- name: install kibana
  import_tasks: "kibana.yml"
  tags: [install,configure]

- name: install logstash
  import_tasks: "logstash.yml"
  tags: [install, configure]

- name: enable services
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
  - elasticsearch
  - kibana
  tags: configure

