---

- name: install kibana
  package:
    name: "kibana={{ kibana_version }}"
    state: present
  tags: install

- name: configure kibana
  template:
    src: "kibana.yml"
    dest: "/etc/kibana/kibana.yml"
  notify: restart kibana
  tags: configure

- name: enable services
  service:
    name: kibana
    enabled: yes
    state: started
  tags: configure, install
