- name: install tools
  package:
    name:
    - lsscsi
    - open-iscsi
    state: present
  tags: install

- name: configure initiatorname.iscsi
  template:
    src: initiatorname.iscsi
    dest: /etc/iscsi/initiatorname.iscsi
    mode: 0600
  register: res_initiatorname
  notify:
    - restart iscsid
    - iscsiadm discovery
  tags: configure

- name: configure iscsid.conf
  template:
    src: iscsid.conf
    dest: /etc/iscsi/iscsid.conf
    mode: 0644
  notify: restart iscsid
  tags: configure
