- debug: msg="openvpn_client_remotes={{ openvpn_client_remotes }}"
- debug: msg="soc_vpn_servers={{ soc_vpn_servers }}"

- name: "Ensure /etc/hosts contains server name from item.remote"
  register: result
  command: "grep '.*{{ item.remotes | first | split(' ') | first }}.*' /etc/hosts"
  loop:  "{{ soc_vpn_servers }}"
  changed_when: false
  failed_when: >
    (result is not defined) or
    (result.rc > 0)

- name: deploy x509
  copy:
    src: "{{ item.src }}"
    dest: "/etc/openvpn/{{ openvpn_instance }}/{{ item.name }}"
    mode: 0600
  with_items:
    - name: client.crt
      src: "{{ openvpn_config.client_crt }}"
    - name: client.key
      src: "{{ openvpn_config.client_key }}"
  tags: 
  - configure
  - x509
  notify: restart openvpn

- name: generate client configuration
  template:
    src: client.conf
    dest: "/etc/openvpn/{{ openvpn_instance }}.conf"
  tags: configure
  notify: restart openvpn
