- name: install dependencies
  apt: name={{ item }}
  with_items:
  - python-mysqldb

- name: create postfix database
  mysql_db:
    name={{ mail_db_name }}
    state=present
  register: mailadmin_db_present

- name: create postfix user
  mysql_user:
    name={{ mail_db_user }}
    password={{ mail_db_password }}
    priv='{{ mail_db_name }}.*:ALL'
    state=present

- name: copy access.sql file
  copy:
    src="access.sql"
    dest="/tmp/access.sql"
    owner=root group=root mode=600

- name: import access table
  mysql_db:
    name={{ mail_db_name }}
    state=import
    target=/tmp/access.sql
  when: mailadmin_db_present.changed == True
