- name: create reverse ssh user
  user:
    name: "{{ reverse_ssh_client_user }}"
    comment: "Reverse SSH to {{ reverse_ssh_server_addr }}"

- name: deploy script
  template:
    src: cat.sh
    owner: "{{ reverse_ssh_client_user }}"
    mode: 0750
    dest: "/home/{{ reverse_ssh_client_user }}/cat.sh"

- name: prepare directories
  file:
    path: "/home/{{ reverse_ssh_client_user }}/.ssh"
    state: directory
    owner: "{{ reverse_ssh_client_user }}"
    mode: 0500

#TODO: replace with known_hosts:
- name: generate known_hosts 
  template:
    src: known_hosts
    dest: "/home/{{ reverse_ssh_client_user }}/.ssh/known_hosts"
    owner: "{{ reverse_ssh_client_user }}"
    mode: 0640

- name: generate private keys
  openssh_keypair:
    path: "/home/{{ reverse_ssh_client_user }}/.ssh/id_ed25519"
    owner: "{{ reverse_ssh_client_user }}"
    type: ed25519
  register: "reverse_ssh_client_key"

- name: generate authorized_keys
  authorized_key:
    user: "{{ reverse_ssh_server_user }}"
    state: present
    key: "{{ reverse_ssh_client_key.public_key }} {{ reverse_ssh_client_user }}@{{ inventory_hostname }}"
    key_options: "command=\"/bin/cat\",permitopen=\"127.0.0.1:{{ 2000+reverse_ssh_client_id }}\""
  delegate_to: "{{ reverse_ssh_server_host }}"

- name: configure systemd
  template:
    src: systemd
    dest: /etc/systemd/system/reverse-ssh.service
  notify: reload systemd

