- name: install cluster sw
  apt: 
    name: 
    - pacemaker 
    - corosync 
    - crmsh
    - fence-agents
    - drbd-utils
    - ocfs2-tools
  tags: install

- name: prepare directories
  file: 
    path: "{{item}}"
    state: directory
    owner: root
    group: root
  with_items:
  - "/etc/systemd/system/pacemaker.service.d/"

- name: configure pacemaker systemd override
  copy:
    src: pacemaker_override.conf
    dest: "/etc/systemd/system/pacemaker.service.d/override.conf"
  tags: configure

- name: deploy corosync authkey
  copy:
    content: "{{ cluster.authkey|b64decode }}" 
    dest: /etc/corosync/authkey
    mode: 0400
    owner: root
    group: root
  tags: configure

- name: configure corosync
  template:
    src: corosync.conf
    dest: /etc/corosync/corosync.conf
  tags: configure

- name: reload systemd configuration
  systemd:
    daemon_reload: yes

- name: disable system services
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
  - drbd
  - libvirt-guests

- name: restart corosync
  systemd:
    name: corosync
    state: restarted

- name: restart pacemaker
  systemd:
    name: pacemaker
    state: restarted


# TODO:
# configure drbd / ocfs
# create-md on both
# make primary + override on first
# mkfs.ocfs2 -L "shared" //dev/drbd/by-res/shared
#
