- name: install cluster sw
  apt:
    name:
    - pacemaker
    - corosync
    - crmsh
    - pcs
    - fence-agents
    - drbd-utils
    - ocfs2-tools
    - dlm-controld
  tags: install

- name: install additional cluster sw (jammy)
  apt:
    name:
    - resource-agents-extra
  when: ansible_distribution_major_version|int >= 22
  tags: install

- name: prepare directories
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
  with_items:
  - "/etc/systemd/system/pacemaker.service.d/"

- name: configure pacemaker systemd override
  copy:
    src: pacemaker_override.conf
    dest: "/etc/systemd/system/pacemaker.service.d/override.conf"
  tags: configure
  notify:
    - restart corosync
    - restart pacemaker

- name: deploy corosync authkey
  copy:
    content: "{{ cluster.authkey|b64decode }}"
    dest: /etc/corosync/authkey
    mode: 0400
    owner: root
    group: root
  tags: configure
  notify:
    - restart corosync
    - restart pacemaker

- name: configure corosync
  template:
    src: corosync.conf
    dest: /etc/corosync/corosync.conf
  tags: configure
  notify:
    - restart corosync
    - restart pacemaker

- name: reload systemd configuration
  systemd:
    daemon_reload: yes

- name: disable system services
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
  - drbd
  - libvirt-guests
  ignore_errors: yes

- name: remove old cluster maintenance scripts
  file:
    path: "/usr/local/bin/{{ item }}"
    state: absent
  with_items:
    - cluster-drain-node.sh
  tags: install

- name: deploy cluster maintenance scripts
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0700
  with_items:
    - cluster-drain.sh
    - cluster-unmove.sh
    - cluster-list-vms.sh
    - cluster-list-obsolete.sh
    - cluster-balance.sh
    - cluster-check.sh
    - cluster-tools.sh
  tags:
  - install
  - cluster-tools

# TODO:
# configure drbd / ocfs
# create-md on both
# make primary + override on first
# mkfs.ocfs2 -L "shared" //dev/drbd/by-res/shared
#
