- name: install dependencies
  yum:
    name: 
    - pygpgme 
    - yum-utils
    state: present

- name: install varnish41 yum repo
  copy:
    src: yum-varnish41-repo
    dest: /etc/yum.repos.d/varnish41.repo

- name: enable varnish41 repos
  raw: "yum -q makecache -y --disablerepo='*' --enablerepo='{{ item }}'"
  with_items:
  - "varnish41"
  - "varnish41-source"

- name: install packages (redhat)
  yum: 
    name: 
    - pkgconfig 
    - varnish-libs-devel 
    state: present

