- name: apt-get update and upgrade
  apt:
    update_cache: true
    upgrade: safe
    autoremove: true

- name: apt-get dist-upgrade
  apt:
    upgrade: dist
    autoremove: true
  register: "upgrade_kernel"

- meta: flush_handlers

- name: reboot host into new kernel
  #reboot:
  debug: 
    msg: consider rebooting
  when: upgrade_kernel.changed

