- name: check if zabbix-release is available
  command: dpkg-query -W zabbix-release
  register: res
  check_mode: no
  ignore_errors: True

- name: check if we need to reinstall zabbix
  set_fact:
    monitor_reinstall_zabbix: "{{ res.stdout is search(\"3\\.[024]\") or res.stdout is not search(ansible_distribution_release) }}"
    check_mode: no
    
- name: remove old zabbix-release 
  apt:
      name: zabbix-release
      state: absent
      purge: yes
      autoremove: yes
  when: monitor_reinstall_zabbix

- name: download and install zabbix-release for Ubuntu
  import_tasks: ubuntu_install.yml
  when: ansible_distribution == 'Ubuntu' and monitor_reinstall_zabbix

- name: download and install zabbix-release for Debian
  import_tasks: debian_install.yml
  when: ansible_distribution == 'Debian' and monitor_reinstall_zabbix
