- name: check if zabbix-release is available
  command: dpkg-query -W zabbix-release
  register: res
  check_mode: no
  ignore_errors: True

- name: remove old zabbix-release
  apt:
      name: zabbix-release
      state: absent
      purge: yes
  when: res.stdout is search("3\.[024]")

- name: download and install zabbix-release
  import_tasks: ubuntu_install.yml
  when: res is failed or ( res.stdout is search("3\.[024]") )
