 - name: make sure dest dir exists
   file:
     path: "{{ dest_dir }}"
     state: directory

 - name: deploy ca chain
   copy:
     src: "{{ ca_dir }}/chained-ca{{ src_name_suffix }}.crt"
     dest: "{{ dest_dir }}/{{ ca_name }}"
   when: ca_name is defined and ca_name != ""

 - name: deploy cert
   copy:
     src: "{{ ca_dir }}/{{ hostname }}{{src_name_suffix}}.crt"
     dest: "{{ dest_dir }}/{{ crt_name }}"
   when: crt_name is defined and crt_name != ""

 - name: deploy key
   copy:
     src: "{{ ca_dir }}/{{ hostname }}{{src_name_suffix}}.key"
     dest: "{{ dest_dir }}/{{ key_name }}"
   when: key_name is defined and key_name != ""

 - name: deploy pem
   copy:
     src: "{{ ca_dir }}/{{ hostname }}.pem"
     dest: "{{ dest_dir }}/{{ pem_name }}"
   when: pem_name is defined and pem_name != ""

 # to make elastic happy :)
 - name: generate fullchain cert
   copy:
     dest: "{{ dest_dir }}/{{ fullchain_name }}"
     content: |
       {{ lookup('ansible.builtin.file', '{{ ca_dir }}/{{ hostname }}{{src_name_suffix}}.crt') }}
       {{ lookup('ansible.builtin.file', '{{ ca_dir }}/signing-ca{{ src_name_suffix }}.crt') }}
       {{ lookup('ansible.builtin.file', '{{ ca_dir }}/root-ca{{ src_name_suffix }}.crt') }}
   when: fullchain_name is defined and fullchain_name != ""
