 - name: make sure dest dir exists
   file:
     path: "{{ dest_dir }}"
     state: directory

 - name: deploy ca chain
   copy:
     src: "{{ ca_dir }}/ca/certs/chained-ca.sha256.4096.crt"
     dest: "{{ dest_dir }}/{{ ca_name }}"

 - name: deploy server cert
   copy:
     src: "{{ ca_dir }}/servers/certs/{{ hostname }}.sha256.4096.crt"
     dest: "{{ dest_dir }}/{{ crt_name }}"

 - name: deploy server key
   copy:
     src: "{{ ca_dir }}/servers/keys/{{ hostname }}.sha256.4096.key"
     dest: "{{ dest_dir }}/{{ key_name }}"

