 - name: make sure dest dir exists
   file:
     path: "{{ dest_dir }}"
     state: directory

 - name: deploy ca chain
   copy:
     src: "{{ ca_dir }}/ca/certs/chained-ca.{{simplepki_message_digest}}.{{ simplepki_key_size }}.crt"
     dest: "{{ dest_dir }}/{{ ca_name }}"
   when: ca_name is defined and ca_name != ""

 - name: deploy cert
   copy:
     src: "{{ ca_dir }}/{{ type }}/certs/{{ hostname }}.{{simplepki_message_digest}}.{{ simplepki_key_size }}.crt"
     dest: "{{ dest_dir }}/{{ crt_name }}"
   when: crt_name is defined and crt_name != ""

 - name: deploy key
   copy:
     src: "{{ ca_dir }}/{{ type }}/keys/{{ hostname }}.{{simplepki_message_digest}}.{{ simplepki_key_size }}.key"
     dest: "{{ dest_dir }}/{{ key_name }}"
   when: key_name is defined and key_name != ""

 - name: deploy pem
   copy:
     src: "{{ ca_dir }}/{{ type }}/pem/{{ hostname }}.pem"
     dest: "{{ dest_dir }}/{{ pem_name }}"
   when: pem_name is defined and pem_name != ""

