- name: install zabbix-agent and dependencies
  package:
    name: 
    - python-mysqldb
    - logtail
    - sudo
    - jq
    - zabbix-agent
    - zabbix-sender
    state: latest
  notify: restart zabbix-agent

- name: make sure zabbix_agentd.d directory is present
  file:
    path: "/etc/zabbix/zabbix_agentd.d/"
    state: directory
    mode: 0755

- name: configure zabbix-agent
  template:
    src: "zabbix_agentd.conf"
    dest: "/etc/zabbix/zabbix_agentd.conf"
  tags: configure
  notify: restart zabbix-agent

- name: delete default user parameter files
  file:
    path: "/etc/zabbix/zabbix_agentd.d/{{item}}"
    state: absent
  with_items:
  - userparameter_mysql.conf
  - mysql.conf
  - vfs.conf
  - zabbix_mdraid.conf
  tags: configure
  notify: restart zabbix-agent

- name: custom user parameters
  template:
    src: "{{ item }}"
    dest: "/etc/zabbix/zabbix_agentd.d/{{ item }}"
    owner: "root"
    group: "zabbix"
    mode: 0640
  with_items: "{{ monitor_user_parameters }}"
  tags: configure
  notify: restart zabbix-agent

- name: monitoring scripts
  copy:
    src: "scripts/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: "root"
    mode: 0755
  with_items: "{{ monitor_scripts }}"
  tags: configure
  notify: restart zabbix-agent

- name: make sure zabbix home directory is present
  file:
    path: "/var/lib/zabbix/"
    state: directory
    mode: 0700
    owner: zabbix
    group: zabbix

- name: create mysql user for monitoring
  mysql_user:
    name: "{{ monitor_sql_user }}"
    password: "{{ monitor_sql_password }}"
    priv: '*.*:USAGE'
    state: present
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_password }}"
  tags: configure
  when: monitor_sql_password is defined

- name: generate .my.cnf for monitoring
  template:
    src: "my.cnf"
    dest: "/var/lib/zabbix/.my.cnf"
    owner: "zabbix"
    group: "zabbix"
    mode: 0600
  tags: configure
  when: monitor_sql_password is defined

- name: generate zabbix_agentd.psk
  template:
    src: "zabbix_agentd.psk"
    dest: "/etc/zabbix/zabbix_agentd.psk"
    owner: "zabbix"
    group: "zabbix"
    mode: 0600
  when: monitor_psk is defined
  tags: configure
  notify: restart zabbix-agent

- name: configre cron.d
  template:
    src: "cron"
    dest: "/etc/cron.d/zabbix-agent"
    mode: 0440
  tags: configure
  notify: restart cron

- name: enable zabbix-agent service
  service:
    name: "zabbix-agent"
    enabled: yes
  tags: configure
  notify: restart zabbix-agent

- name: allow zabbix user to run specific commands as root
  copy:
    src: "zabbix_sudoers"
    dest: "/etc/sudoers.d/zabbix"
    owner: "root"
    mode: 0640
  tags: configure

- name: enable periodic apt-get update
  template:
    src: "10periodic"
    dest: "/etc/apt/apt.conf.d/10periodic"
    owner: "root"
  tags: configure

- name: install logging dependencies
  package:
    name: logrotate
    state: present

- name: rotate zabbix logs
  copy:
    src: zabbix-agent-logrotate
    dest: /etc/logrotate.d/zabbix-agent
  tags: configure
