
- name: include host in bacula-dir.conf
  lineinfile:
    path: "/etc/bacula/bacula-dir.conf"
    regexp: '/{{backup_client}}\.conf$'
    line: "@/etc/bacula/hosts/{{backup_client}}.conf"
  notify: restart bacula-dir

- name: create host config directory
  file:
    path: /etc/bacula/hosts/
    state: directory

- name: generate host configuration
  template:
    src: host.conf
    dest: "/etc/bacula/hosts/{{backup_client}}.conf"
  notify: restart bacula-dir
