- name: install logstash
  package:
    name: logstash
  notify: restart logstash
  tags: install

- name: enable plugins
  logstash_plugin:
    name:  "{{ item }}"
    state: present
  with_items: "{{ logstash_plugins }}"
  notify: restart logstash
  tags: install

- name: enable logstash service
  systemd:
    name: logstash
    enabled: yes
    state: started
  tags: install

