---

- name: install elasticsearch on Debian
  when: ansible_os_family == 'Debian'
  package:
    name: "elasticsearch={{ elastic_version }}"
    state: present
  tags: install

- name: install elasticsearch on other distro
  when: ansible_os_family != 'Debian'
  package:
    name: elasticsearch
    state: present
  tags: install

- name: create data storage
  file:
    path: "{{ elastic_data_path }}"
    state: directory
    owner: elasticsearch
  notify: restart elasticsearch
  tags: configure

- name: make sure subdirs exist
  file:
    path: "/etc/elasticsearch/{{ item }}"
    state: directory
  with_items:
    - jvm.options.d
    - certs

- name: configure elastic
  template:
    src: "{{ item.src }}"
    dest: "/etc/elasticsearch/{{ item.dest }}"
  with_items:
    - src: elasticsearch.yml
      dest: elasticsearch.yml
    - src: jvm.options
      dest: jvm.options.d/jvm.options
  notify: restart elasticsearch
  tags: configure

- name: fix permissions
  file:
    path: /etc/elasticsearch/certs
    mode: 0750
    group: elasticsearch

- name: fix permissions
  file:
    path: "{{ item }}"
    mode: 0660
    group: elasticsearch
  with_items:
    - /etc/elasticsearch/elasticsearch.yml
    - /etc/elasticsearch/elasticsearch.keystore
  tags: configure

- name: prepare systemd override directory
  file:
    path: "/etc/systemd/system/elasticsearch.service.d"
    state: directory
  tags: configure

- name: configure memlock
  copy:
    src: "override.conf"
    dest: "/etc/systemd/system/elasticsearch.service.d/override.conf"
  notify:
    - reload systemctl
  tags: configure

- name: remove limitations on memory
  template:
    src: "limits.conf"
    dest: "/etc/security/limits.d/elasticsearch.conf"
  tags: configure

- name: load limits on session login
  lineinfile:
    path: "/etc/pam.d/common-session"
    line: "session required pam_limits.so"
  tags: configure

- name: generate elastic ldap role mapping
  copy:
    content: |
      monitoring: 
        - "cn=AppElasticAdmin,{{ elastic_ldap_groups_dn }}"
      user:
        - "cn=AppElasticAdmin,{{ elastic_ldap_groups_dn }}"
        - "cn=AppElasticUser,{{ elastic_ldap_groups_dn }}"
    dest: /etc/elasticsearch/role_mapping.yml
  tags: configure
  when: elastic_ldap
  notify: restart elasticsearch

- name: flush handlers
  meta: flush_handlers

- name: enable services
  service:
    name: elasticsearch
    enabled: true
    state: started
  tags: configure, install
