- name: install java runtime environment
  package:
    name: openjdk-8-jre-headless
    state: present
  tags: install

- name: install elastic
  package:
    name: elasticsearch
    state: present
  tags: install
