- name: install squid
  package:
    name: squid
    state: present
  tags: install

- name: configure squid
  template:
    src: squid.conf
    dest: /etc/squid/squid.conf
  tags: configure
  notify: reload squid

- name: configure logrotate
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.d/squid
  tags: configure

- name: ensure service is started and enabled
  service:
    name: squid
    enabled: true
    state: started
