- name: enable and restart supervisor
  service:
    name: "{{ supervisor_service }}"
    enabled: yes
    state: restarted

- name: restart supervisor
  service:
    name: "{{ supervisor_service }}"
    state: restarted
