- name: install filebeat
  package:
    name: filebeat
  notify: restart filebeat
  tags: install

- name: enable filebeat service
  systemd:
    name: filebeat
    enabled: yes
    state: started
  tags: install

