- name: make sure block device exists
  file:
    path: "{{ virtual.disk_blk | default('/dev/mapper/'+virtual.name) }}"

- name: "lock preseeding mutex for this vm"
  shell: "tempfile -n \"{{ virtual_dir }}/preseed/{{ virtual.name }}.lock\""
  ignore_errors: yes
  register: virtual_preseed_lock

- name: "check if configuration file is present"
  stat:
    path: "{{ virtual_dir }}/conf/{{ virtual.name }}.xml"
  register: virtual_existing_conf

- name: "check if libvirt knows this vm"
  virt:
    name: "{{ virtual.name }}"
    command: status
  ignore_errors: yes
  register: virtual_existing_vm

#- debug:
#    msg: "virtual_preseed_lock={{ virtual_preseed_lock }}"
#- debug:
#    msg: "virtual_existing_conf={{ virtual_existing_conf }}"
#- debug:
#    msg: "virtual_existing_vm={{ virtual_existing_vm }}"

- name: "run only when we got exclusive lock and no conf file is present"
  meta: end_host
  when: virtual_preseed_lock.rc|default(0) != 0 or virtual_existing_conf.stat.exists == True or 'status' in virtual_existing_vm 

- name: prepare preseed dir for this host
  file:
    path: "{{ virtual_dir }}/preseed/{{ virtual.name }}/"
    state: directory

- name: prepare config files
  template:
    src: "{{ item }}"
    dest: "{{ virtual_dir }}/preseed/{{ virtual.name }}/{{ item }}"
  with_items:
    - cloud_init.cfg
    - network.cfg

- name: generate cloud confgiuration 
  shell: cloud-localds --network-config=network.cfg seed.qcow2 cloud_init.cfg
  args:
    chdir: "{{ virtual_dir }}/preseed/{{ virtual.name }}"

- name: prepare base disk
  shell: qemu-img dd if={{ virtual_image }} of={{ virtual.disk_blk | default('/dev/mapper/'+virtual.name) }} bs=1M

- name: create vm using virt-install
  shell: virt-install \
    --name="{{ virtual.name }}" \
    --arch=x86_64 \
    --vcpus="{{ virtual.cpus }}" \
    --ram="{{ virtual.ram }}" \
    --os-type=linux \
    --os-variant="{{ virtual_version }}" \
    --machine="{{ virtual.machine | default('ubuntu') }}" \
    --virt-type kvm \
    --hvm \
    --connect=qemu:///system \
    --network=bridge:"{{ networking[virtual.default_interface | default('eth0')].virtual_host_iface }}",model=virtio,mac={{ networking[virtual.default_interface | default('eth0')].ether }} \
    --boot hd \
    --disk path="{{ virtual.disk_blk | default("/dev/mapper/"+virtual.name) }}",device=disk,bus=virtio,cache=none \
    --disk path="{{ virtual_dir }}/preseed/{{ virtual.name }}/seed.qcow2",device=cdrom \
    --graphics=vnc,port=-1 \
    --video vmvga \
    --noautoconsole \
    --debug \
    --noreboot

- name: wait for vm to finish preseeding
  virt:
    command: info
  register: virtual_install
  until: virtual_install[virtual.name].state == "shutdown"
  retries: 20
  delay: 60
