- package: 
    name: 
      - arpwatch
      - tcpdump
      - rsync
    state: present

- name: configure arpwatch
  copy:
    dest: '/etc/arpwatch/{{ hole_interface }}.iface'
    content: |
      IFACE_ARGS="-Q"

- name: enable arpwatch
  service:
    name: "arpwatch@{{ hole_interface }}"
    enabled: true
    state: started

- name: create directory structure
  file:
    path: "{{ hole_dir }}/data/"
    owner: tcpdump
    group: tcpdump
    state: directory

- name: deploy scripts
  template:
    src: '{{ item }}'
    dest: '{{ hole_dir }}/{{ item }}'
    mode: 0755
  with_items:
    - capture.sh
    - purge.sh

- name: run purge via cron
  copy:
    content: |
      10 * * * * root /opt/hole/purge.sh
    dest: /etc/cron.d/telescope-hole
    mode: 0644

- name: deploy supervisor config
  template:
    src: "supervisor.conf"
    dest: "{{ supervisor_conf_d }}/hole{{ supervisor_conf_suffix }}"
    # <3 supervisor :)
  notify: restart supervisor

