name: minio
services:
  minio:
    image: quay.io/minio/minio:{{ minio_version }}
    container_name: {{ minio_container_name }}
{% if minio_cluster | default(False) %}
{% if minio_use_tls %}
    command: server --console-address ":9001" https://{{ minio_cluster }}:{{ minio_api_port }}/data
{% else %}
    command: server --console-address ":9001" http://{{ minio_cluster }}:{{ minio_api_port }}/data
{% endif %}
{% else %}
    command: server --console-address ":9001" /data
{% endif %}
    ports:
      - "{{ minio_api_port }}:{{ minio_api_port }}"
      - "{{ minio_console_port }}:9001"
    volumes:
      - data:/data
{% if minio_use_tls %}
      - ./certs:/root/.minio/certs
{% endif %}
    healthcheck:
{% if minio_use_tls %}
      test: ["CMD", "curl", "-f", "-k", "https://localhost:{{ minio_api_port }}/minio/health/live"]
{% else %}
      test: ["CMD", "curl", "-f", "http://localhost:{{ minio_api_port }}/minio/health/live"]
{% endif %}
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: "{{ minio_admin_user }}"
      MINIO_ROOT_PASSWORD: "{{ minio_admin_password }}"
      MINIO_ADDRESS: ":{{ minio_api_port }}"
      MINIO_CONSOLE_ADDRESS: ":9001"
      #VIRTUAL_HOST: "{{ inventory_hostname }}"
      #VIRTUAL_PORT: 8080
volumes:
  data:

