- name: start vm
  virt:
    name: "{{ virtual.name }}"
    state: running
  register: virtual_start

- name: wait for vm to start
  wait_for_connection:
    connect_timeout: 5
    sleep: 5
    delay: 10
    timeout: 300
  delegate_to: "{{ virtual.fqdn | default(virtual.name) }}"
  when: virtual_start is changed
