- name: reload systemctl
  systemd:
    daemon_reload: yes

- name: concat ssl
  shell: /etc/haproxy/concat_ssl.sh

- name: restart varnish
  service: 
    name: varnish
    state: restarted

- name: restart haproxy
  service: 
    name: haproxy
    state: restarted

- name: restart supervisor
  service:
    name: "{{ supervisor_service }}"
    state: restarted
