- name: add host to zabbix server
  become: false
  vars:
    monitor_host: "{{ inventory_hostname }}"
    monitor_addr: "{{ ansible_default_ipv4.address }}"
  local_action:
    module: zabbix_host
    server_url: "{{ monitor_url }}"
    login_user: "{{ monitor_admin_login }}"
    login_password: "{{ monitor_admin_password }}"
    host_name: "{{ monitor_host }}"
    visible_name: "{{ monitor_host }}"
    host_groups:
    - "{{ monitor_group }}"
    link_templates: "{{ monitor_templates | unique }}"
    status: enabled
    state: present
    inventory_mode: automatic
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: "{{ monitor_addr }}"
        dns: ""
        port: 10050
    tls_connect: 2 # psk
    tls_accept: 2  # psk
    tls_psk_identity: "{{ monitor_host }}"
    tls_psk: "{{ monitor_psk }}"
    proxy: "{{ monitor_proxy }}"
    validate_certs: false

- name: Create zabbix macros
  become: false
  local_action:
    module: zabbix_hostmacro
    server_url: "{{ monitor_url }}"
    login_user: "{{ monitor_admin_login }}"
    login_password: "{{ monitor_admin_password }}"
    host_name: "{{ inventory_hostname }}"
    macro_name: "{{ item['macro_name'] }}"
    macro_value: "{{ item['macro_value'] }}"
    state: present
    validate_certs: false
  with_items: "{{ hostvars[inventory_hostname]['monitor_macro'] | default([]) }}"
