- name: install virtualization packages
  package:
    name:
    - libvirt-bin
    - qemu-kvm
    - python3-libvirt
    - virtinst
    - unar
    - bridge-utils
    - vlan
    - irqbalance
    - kpartx
  tags: install

- name: prepare directories
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
  with_items:
  - "{{ virtual_dir }}/conf/"
  - "{{ virtual_dir }}/preseed/"

- name: configure qemu-kvm
  template:
    src: qemu-kvm.defaults
    dest: /etc/default/qemu-kvm
  tags:
  - install
  - configure

- name: configure lvm (blacklist)
  template:
    src: lvm.conf
    dest: /etc/lvm/lvm.conf
  tags:
  - configure

- name: get rid of default networking
  shell:
    virsh net-destroy default 2>&1 || true
  tags: install
