- name: install virtualization packages 
  apt: 
    name: 
    - libvirt-bin 
    - qemu-kvm
    - virtinst
    - unar
    - bridge-utils
    - vlan
    - irqbalance
    - kpartx
  tags: install

- name: configure qemu-kvm
  template:
    src: qemu-kvm.defaults
    dest: /etc/default/qemu-kvm
  tags: 
  - install
  - configure

- name: get rind of default networking
  shell:
    virsh net-destroy default 2>&1 || true
  tags: install
