- name: install virtualization packages
  package:
    name:
    - python3-libvirt
    - python3-lxml
    - virtinst
    - unar
    - bridge-utils
    - vlan
    - irqbalance
    - kpartx
    - cloud-image-utils
  tags: install

- name: install virtualization packages
  package: 
    name:
    - libvirt-bin
    - qemu-kvm
  tags: install
  when: ansible_os_family == "Debian" and ansible_distribution_major_version|int <= 18

- name: install virtualization packages
  package: 
    name:
    - libvirt-daemon-system
    - libvirt-clients
    - qemu-system-x86
  when: ansible_os_family == "Debian" and ansible_distribution_major_version|int > 18
  tags: install

- name: prepare directories
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
  with_items:
  - "{{ virtual_dir }}/conf/"
  - "{{ virtual_dir }}/preseed/"

- name: configure qemu-kvm
  template:
    src: qemu-kvm.defaults
    dest: /etc/default/qemu-kvm
  tags:
  - install
  - configure

- name: configure lvm (blacklist)
  template:
    src: lvm.conf
    dest: /etc/lvm/lvm.conf
  tags:
  - configure

#XXX: ugly
- name: get rid of default networking
  shell:
    virsh net-destroy default 2>&1 || true
  changed_when: false
  tags: install
