- name: install dependencies
  package:
    name:
      - apt-transport-https
      - openjdk-8-jre-headless
    state: present
  tags: install

- name: setup java
  lineinfile:
    path: /etc/environment
    line: 'JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"'

- name: add thehive-project key
  apt_key:
    url: "https://raw.githubusercontent.com/TheHive-Project/TheHive/master/PGP-PUBLIC-KEY"
    keyring: /etc/apt/trusted.gpg.d/thehive.gpg
    state: present
  tags: install

- name: add cassandra key
  apt_key:
    url: "https://downloads.apache.org/cassandra/KEYS"
    keyring: /etc/apt/trusted.gpg.d/cassandra.gpg
    state: present
  tags: install

- name: add thehive-project repo
  apt_repository:
    repo: "deb [arch=all] https://deb.thehive-project.org release main"
    update_cache: yes
  tags: install

- name: add cassandra repo
  apt_repository:
    repo: "deb https://debian.cassandra.apache.org 311x main"
    update_cache: yes
  tags: install

- name: install packages
  package:
    name:
      - thehive4
      - cassandra
    state: present
  tags: install

- name: prepare directories
  file:
    path: "{{ item }}"
    state: directory
    owner: thehive
    group: thehive
  with_items:
    - /opt/thehive4/index
    - /opt/thehive4/files

- name: configure thehive
  template:
    src: "{{ item }}"
    dest: "/etc/thehive/{{ item }}"
    owner: root
    group: thehive
    mode: 0640
  with_items:
    - application.conf
    - secret.conf
  notify: restart thehive
  tags: configure

- name: get currect casandra cluster name
  shell: |
    cqlsh --no-color -e "SELECT cluster_name FROM system.local WHERE key='local';" 2>&1 | grep -A 1 '\-\-\-' | tail -n 1 | sed 's/^[ ]*//'
  register: cassandra_cluster_name

- debug:
    msg: "current cassandra cluster name is '{{ cassandra_cluster_name.stdout }}'"
  failed_when: cassandra_cluster_name.stdout == ""

- name: change casandra cluster name
  shell: | 
    cqlsh --no-color -e "UPDATE system.local SET cluster_name = 'thp' where key='local';"
    nodetool flush
  when: cassandra_cluster_name.stdout != "thp"

- name: configure cassandra
  template:
    src: cassandra.yaml
    dest: "/etc/cassandra/cassandra.yaml"
  notify: restart cassandra
  tags: configure
  when: false

