- name: install dependencies
  package:
    name:
    - software-properties-common
    - apt-transport-https
    - git
  tags: install

#- name: add golang repository
#  apt_repository:
#    repo: ppa:longsleep/golang-backports
#    state: present
#    update_cache: yes
#  tags: install

#XXX: https://github.com/ansible/ansible/issues/42534
- name: add repo key
  apt_key:
    url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x52B59B1571A79DBC054901C0F6BC817356A3D45E"
    state: present

- name: add golang repo
  apt_repository:
    repo: "deb http://ppa.launchpad.net/longsleep/golang-backports/ubuntu {{ ansible_distribution_release }} main"
    filename: php
    state: present
    update_cache: yes

- name: install golang
  package:
    name: golang-1.19
  tags: install
