- name: sysctl flush routes
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    ignoreerrors: yes #ignore errors about unknown keys
  with_items: 
  - { key: "net.ipv4.route.flush", value: "1"}
  - { key: "net.ipv6.route.flush", value: "1"}

