---

- name: setup chrony on ubuntu
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('18.0', operator='ge', strict=True)
  include_tasks: chrony_ubuntu.yml

- name: setup chrony on debian
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_version is version('11', operator='ge')
  include_tasks: chrony_debian.yml
