- name: uninstall ntpsec
  package:
    name: ntpsec
    state: absent
  tags: install

- name: install ntp
  package:
    name:
     - ntp
     - ntpdate
    state: present
  tags: install

- import_tasks: run-ntpdate.yml
  tags: always

- name: configure ntp
  template:
    src: ntp.conf
    dest: /etc/ntp.conf
    owner: root
    mode: 0640
  tags: configure
  notify: restart ntp
