- block:
  - name: uninstall chrony
    package:
      name: "{{item}}"
      state: absent
    with_items:
    - chrony
    tags: install

  - name: disable timesyncd
    systemd:
      name: "{{item}}"
      enabled: no
      state: stopped
    with_items:
    - systemd-timesyncd
    failed_when: false
    tags: install

  - name: install ntp
    package:
      name: 
      - ntp
      - ntpdate
      state: present
    tags: install

  - name: check time difference
    shell: >
      ntpdate -q {{ ntp_servers[0] | quote }} |
      tail -n1 |
      sed -nE 's/.*offset[[:space:]:]+([+-]?[0-9]+\.[0-9]+).*/\1/p;
               s/.* ([+-]?[0-9]+\.[0-9]+) \+\/-.*/\1/p'
    register: ntpdate_offset
    changed_when: false
    check_mode: no
    ignore_errors: true
    tags:
    - ntpdate
    - configure

  - set_fact:
      ntpdate_offset_seconds: "{{ ntpdate_offset.stdout | float | abs }}"

  - debug: 
      msg: "ntp offset {{ ntpdate_offset_seconds }}"

  - name: stop ntp
    service:
      name: "{{ ntp_service }}"
      state: stopped
    when: ntpdate_offset_seconds | int > 5
    notify: restart ntp
    tags:
    - ntpdate
    - configure

  - name: syncronize time
    command: ntpdate {{ ntp_servers[0] | quote }}
    ignore_errors: true
    when: ntpdate_offset_seconds | int > 5
    tags:
    - ntpdate
    - configure

  #TODO: centos/redhat
  - name: configure ntp
    template:
      src: "{{ ntp_template | default('ntp.conf') }}"
      dest: "/etc/ntp.conf"
      owner: root
      mode: 0640
    tags: configure
    notify: restart ntp

  #TODO: bionic?
  - name: remove ntpdate if-up script (blocks ntp on startup)
    file:
      path: "/etc/network/if-up.d/ntpdate"
      state: absent
    tags: configure
    notify: restart ntp
